name: ChatKuy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    name: Build & Test
    runs-on: self-hosted
    timeout-minutes: 45

    concurrency:
      group: flutter-ci
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          cache: false

      # Cache Pub Dependencies
      - name: Cache Pub
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-${{ runner.os }}-${{ hashFiles('pubspec.lock') }}

      # Install dependencies (offline if possible)
      - name: Install dependencies
        run: |
          flutter pub get || flutter pub get --offline


      - name: Generate with Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run flutter test
        run: flutter test --no-pub

      - name: Build APK
        run: |
          flutter build apk \
            --release \
            --obfuscate \
            --split-debug-info=build/flutter_mapping \
            --no-shrink \
            --no-tree-shake-icons \
            --build-number=${{ github.run_number }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

  cd:
    name: Distribute APK
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release

      - name: Generate release notes
        run: |
          # git log -6 --pretty=format:"- %s by %an <%ae>" > release_notes.txt
          git log -6 --pretty=format:"- %s by %an" > release_notes.txt

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: app-release.apk
          releaseNotesFile: release_notes.txt
